from django import forms

from .models import * # importar en la carpeta ctrl_comb...

# PARA GENERAR EL FORMULARIO DE DJANGO...

class MarkForm(forms.ModelForm):  # clase para heredar... modelform... del modelo..
    class Meta: # indicaremos cual es el modelo.. cuya instancias son clases... ejemplo Mark... de models...
        model = Mark
        fields = "__all__" # que incluya todos los campos.. aca ver para cargar lista.... en orden tambien todo.. "__all__"
        


    # sobreescribir el init de formulario, eventos de formularios...
    def __init__(self,*args,**kwargs):
        # ejecutar la funcionalidad de la clase padre... model form..
        super().__init__(*args,**kwargs) # se ejecute en init la clase padre.. y se le pase los argumentos y kwargs...
        # recorrer todos los elementos que tenga el modelo...
        for field in iter(self.fields): # cada iteracion es field...
            self.fields[field].widget.attrs.update({   # definir como diccionario, preguntar por field el campo que estamos iterando
                # para poder poner la clase usar widget... y modificar el atributo con attrs.update ... y le pasamos como diccionario
                # el elemento a modificar la clase y valor de esa clase... form-control de bootstrap...
                'class':'form-control'
            })

# tenemos formulario de MARCA
# AHORA EL DE MODELO...

class ModeloForm(forms.ModelForm): # heredar de modelform..
    class Meta: # instanciar mas clases...
        model = Modelo # aca de models.py extraemos el tipo de datos de Modelo...
        fields = ["mark","descript"] # que incluya todos los campos en ese orden... el all no involucra el orden..
        # que vaya primero la marca y luego el descript... para seleccionar en el formulario de modelos en catalogos...


class VehiculoForm(forms.ModelForm): # heredar de modelform..
    class Meta: # instanciar mas clases...
        model = Vehiculo # aca de models.py extraemos el tipo de datos de vehiculo...
        fields = ["modelo","register","year","tipo","unidad_medida"] # que incluya todos los campos en ese orden... el all no involucra el orden..
        # tiene que coincidir en models... OJO de ctrl_comb...
        # que vaya primero la marca y luego el descript... para seleccionar en el formulario de modelos en catalogos...
        # agregar en vehiculomodal.html en el formulario...
