from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import * # importar vistas genericas de django...
from django.urls import reverse_lazy # cargar una lista, una URL...
from django.db.models import Q # importar objetos Q PARA CONSULTAS BASE DE DATOS...
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger # PARA PAGINACION...
from django.http import JsonResponse # respuesta con JSON...
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin # para los permisos A MARKLIST Y MODELOLIST... marcas y modelos... que no fije sin login
from django.contrib.auth.decorators import login_required, permission_required # para el JSON o cualquier otro dato adicional poner DECORADOR.... A MODELODT..
# el permisision required es decorador tambien...


from .models import * # importar todo de modelos...
from .forms import * # importar el formulario...
from bases.views import SinAutorizacion,MixinSaveUser # importamos los MIXIN YA DEFINIDOS EN VIEWS DE BASES... mixinsaveuser para
# modificar registros por usuario.... por permisos...


# Create your views here.


# class MarkList(LoginRequiredMixin, ListView): # heredara en listview... poner MIXIN PARA LOGEARSE AL VER...

class MarkList(SinAutorizacion, ListView): # heredara en listview... poner MIXIN PARA LOGEARSE AL VER...
    template_name = "ctrl_comb/mark.html" # la plantilla... pasar el nombre de la plantilla por ruta... listar modelo
    model = Mark # enviar dato a la plantilla...
    context_object_name = "obj" # obj como nombre de contexto... variable de contexto como se usa en mark-list.html vista le pasa a plantilla
    ordering = ["descript"] # listview tiene propiedad que se llama ordering con el campo que se va a usar... con esto tenemos la vista
    login_url = "usuarios:login" # redirecciona a la ruta para logearse al entrar... sin registrarse aun..
    permission_required = "ctrl_comb.view_mark" # USA EL PERMISSIONREQUIRED MIXIN LA CLASE SIN AUTORIZACION ENTONCES AGREGAR PERMISSION REQUIRED
    # esto es para que el user tenga al menos ese permiso de ver marcas...


# trabajaremos con una vista basada en funciones... ES DIFERENTE A LAS PASADAS... cuando hay una funcionalidad que no esta en clases
# usaremos el de funciones para insertar los registros en el macros...

def mark_save(request): # recibe un request... envio del formulario del otro lado... 
    context = {} # en clase envia por default el contexto... en funcion NO, diccionario vacio
    template_name = "ctrl_comb/mark-list.html" # nombre de la plantilla de donde viene el formulario... directorio..
    # el user enviara una peticion post y lo lee en el request y se pregunta por una propiedad meta.. esta intentando insertar o
    # modificar el registro..

    if request.method == "POST": # CAPTURA POR NAME UN ELEMENTO ID O DESCRIPT EN MARK-LIST.HTML PODER VER...
        i = request.POST.get("id") # valor de name... OJO no de ID... DATOS DE LA PLANTILLA..
        d = request.POST.get("descript") # lo mismo para descripcion...
        print(f"************ {request.user} - {i} *******") # para ver el id... por i... ya que tiene el id
        u =  request.user # user
        o = None # si es vacia...

        if i: # si i existe
            o = Mark.objects.filter(id=i).first() # ACA SE VALIDA SI EL REGISTRO YA EXISTE POR LA DESCRIPCION DE MARCA...
        else:
            o = Mark.objects.filter(descript=i).first() # NO OLVIDAR LOS PUTOS PARENTESIS YA QUE NO AGREGA Y DA ERROR... en first y demas
        
        if o: # si o existe... hacer update con el ORM DE DJANGO... AGREGAR EL UM... SI O SI PARA QUE MODIFICA O CREE SINO NO CARGA
            o.descript = d # el nombre de la marca... 
            o.um = u # la columna um de usuario modifica se inicializa  en caso de detectar el id... por object o
            o.save() # se guarda el cambio que se hizo por el id o descripcion de marca...
        else: # si no existe entonces llaamamos...
             # asumir que toda invocacion sera para crear... marca.. para crear usamos el ORM y metemos a un objeto llamado o.. 
            # coincidir.. con mark-list.html...
            o = Mark.objects.create(descript = d, uc = u) # entonces sera a traves de d en descript... OJO esto crea el objeto y lo que se hace 

        # en POST invocacion... LUEGO NECESITAMOS COMUNICARNOS CON UNA PLANTILLA.. METER EN UNA VARIABLE.. consulta y devolver todos los
        # registros...
    obj = Mark.objects.all().order_by("descript") # devolver todos los registros... de marcas.. de la tabla Mark y guardar en el objeto...
    # con SQL trabaja aca... ordenar por el nombre del campo.. no hemos pasado nada a la plantilla para ello el context[]
    
    r = Mark.objects.filter(id = o.id).first() # si el registro se pudo ingresar lo tiene o... r tiene el registro que se agrega..
    context["obj"] = obj # aqui si ya pasa a la plantilla.... todavia aca no se envia necesita un RETURN...
    # actualizar contexto...
    context["reg"] = r # enviar al formulario..
    
    # por render se pasa, request es lo que se recibe en la funcion..., el nombre de la plantilla.. y el contexto...
    return render(request,template_name,context) # luego de esto agregar ruta en urls.py...

def mark_delete(request,pk): # lo mismo que el anterior... salvo que le pasa el primary key... a borrar... mark/pk... ej: mark/6 ...
    context = {}
    template_name = "ctrl_comb/mark-list.html" # nombre de la plantilla de donde viene el formulario... directorio.. 
    # despues de borrar se recargue la tabla.. filtrar primero registro de marca.. usar ORM de queryser
    o = Mark.objects.filter(id=pk).first() # nos devolveria un select * from where id=pk... ORM.. filter devuelve un conjunto no registro.. OJO
    # de esa lista siempre devuelva el 1er registro que cumple esa condicion...
    o.delete()
    # nos queda volver a listar todo..
    obj = Mark.objects.all().order_by("descript") # devolver todos los registros... de marcas.. de la tabla Mark y guardar en el objeto...
    context["obj"] = obj # aqui si ya pasa a la plantilla.... todavia aca no se envia necesita un RETURN...
    return render(request,template_name,context) # luego de esto agregar ruta en urls.py...
    # LUEGO ELABORAR LA RUTA... PARA EL DELETE... EN URLS.PY DE CTRL_COMB...

    # definir vista para mostrar en el formulario un elemento o registro... a buscar.. request es formulario de http...
def mark_edit(request,pk=None): # que reciba el pk pero opcional con None.. puede que no reciba el pk.. en registro nuevo sin id..
    context = {} 
    template_name = "ctrl_comb/mark-frm.html"    # en frm donde vamos a renderizar el valor... OJASO!

    if pk: # si pk EXISTE!
        o = Mark.objects.filter(id=pk).first() # FILTRAR UN ID... despues de capturar el registro llenaremos el formulario con ese reg
        frm = MarkForm(instance=o) # se le pasa como instancia o a MarkForm de forms..
    else: # si no envia pk el registro es NUEVO!
        frm = MarkForm() # se invoca sin NINGUN VALOR..
    
    context["form"] = frm # y le pasamos el frm... al formulario.... en base de datos...
    context["obj"] = o # recibimos el dato del registro... si o no existe sera NULL...
    return render(request,template_name,context) # luego de esto agregar ruta en urls.py...

# crear nueva vista sin considerar el tbl... en mark-list... AGREGAR MIXINS AL MODELO.. SE DEBE HEREDAR
# LOS MIXIN, PRIMERO EL LOGIN, REQUERIMOS QUE EL USER ESTE LOGEADO LUEGO EL PERMISO... VALIDAR AUTENTICACION...


# class ModeloList(LoginRequiredMixin, PermissionRequiredMixin, ListView): # heredara en listview... listado primero mixin y luego clases def
class ModeloList(SinAutorizacion, ListView): # heredara en SinAutorizacion los MIXIN... ahorras en definir el form invalid y el otro... listado primero mixin y luego clases def
    template_name = "ctrl_comb/modelo.html" # la plantilla... pasar el nombre de la plantilla por ruta... listar modelo
    model = Modelo # enviar dato a la plantilla...
    context_object_name = "obj" # obj como nombre de contexto... variable de contexto como se usa en mark-list.html vista le pasa a plantilla
    ordering = ["mark","descript"] # listview tiene propiedad que se llama ordering con el campo que se va a usar... con esto tenemos la vista
    # ordenamiento por marca y descripcion.. VALIDAR QUE EL UESR ESTE AUTENTICADO..
    login_url = "usuarios:login" # para permitir que los usuarios vean los modelos... PEDIRA REGISTRARSE PARA ACCEDER... a modelos en catalogos
    permission_required = "ctrl_comb.view_modelo" # definir el 2do nivel de seguridad... validar permiso dado... que tenga coincida con la vista accedida
    raise_exception = False # propiedad para autenticar.. ESTO ES PARA QUE NO LEVANTE ERROR... EL 403 O 404..
    redirect_field_name = "redirect_to" # redirigir al usuario despues de autenticarse...

    # def form_invalid(self,form): # cuando un formulario no pasa y contiene errores... respuesta...
    #     response = super().form_invalid(form) # ejecucion de la clase padre.. por super() manejo de errores
    #     if self.request.is_ajax(): # si la peticion que se esta enviando es ajax... si es true si lo es... retornar un ERROR
    #         return JsonResponse(form.errors,status=400) # se retorna error...
    #     else: # si no es peticion AJAX SE RETORNA RESPONSE ORIGINAL
    #         return response
    
    # # METODO HANDLE_NO PERMISSION PARA MANIPULAR FORMULARIO CUANDO NO HAY PERMISO...
    # def handle_no_permission(self): # importar de django http el http response redirect... para poder redireccionar si es anonimo..
    #     # que rediriga al login url...
    #     from django.http import HttpResponseRedirect
    #     from django.contrib.auth.models import AnonymousUser
    #     if not self.request.user == AnonymousUser():  # si el user no es anonimo.. ya tiene login o esta autenticado pero no permiso
    #         self.login_url = "pages:forbidden" # sobreescrcibir login_url...
    #     return HttpResponseRedirect(reverse_lazy(self.login_url)) # si es o no anonimo... no hace falta redirigir a login... con reverselazy
    #     # la utlima linea que no se logee sino que presente la pantalla al user si es anonimo... 
    # CTRK+K+C COMENTAR LINEAS SELECCIONADAS para herencia sin copiar a cada rato e ir a bases y views.py...

            

# CREAR VISTA GENERICA DE CREATEVIEW PARA INSERTAR... PARA MODELO

class ModeloNew(CreateView):
    model=Modelo # enviar dato a la plantilla...
    template_name = "ctrl_comb/modelo_form.html" # la plantilla... pasar el nombre de la plantilla por ruta... listar modelo y luego urls.py
    context_object_name = "obj" # obj como nombre de contexto...
    form_class = ModeloForm # el formulario... envio POST de formulario... direccionar la salida que no se presione F5 para eso..
    # propiedad success url... se encarga de redireccionar a plantilla, en este caso a lista de modelos..
    success_url = reverse_lazy('control:modelo_list') # para la url.... control es el estatico..

# CREAR VISTA PARA EDITAR REGISTROS...

class ModeloEdit(UpdateView): # update es recargar... no olvidar agregar vista en rutas... urls.py de ctrl_comb...
    model=Modelo # enviar dato a la plantilla...
    template_name = "ctrl_comb/modelo_form.html" # la plantilla... pasar el nombre de la plantilla por ruta... listar modelo y luego urls.py
    context_object_name = "obj" # obj como nombre de contexto...
    form_class = ModeloForm # el formulario... envio POST de formulario... direccionar la salida que no se presione F5 para eso..
    # propiedad success url... se encarga de redireccionar a plantilla, en este caso a lista de modelos..
    success_url = reverse_lazy('control:modelo_list') # para la url.... control es el estatico..



# CREAR VISTA PARA BORRAR REGISTROS... BORRAR REGISTROS...

class ModeloDelete(DeleteView): # delete es borrado... no olvidar agregar vista en rutas... urls.py de ctrl_comb...
    model=Modelo # enviar dato a la plantilla...
    template_name = "bases/delete.html" # OJO! APUNTA A BASES... la plantilla... pasar el nombre de la plantilla por ruta... listar modelo y luego urls.py
    context_object_name = "obj" # obj como nombre de contexto...
    # propiedad success url... se encarga de redireccionar a plantilla, en este caso a lista de modelos..
    success_url = reverse_lazy('control:modelo_list') # para la url.... control es el estatico..


# PARA CAMBIAR LOS REGISTOS... DE MODELOS...

class ModeloEditModal(SinAutorizacion,MixinSaveUser,UpdateView): # update es recargar... no olvidar agregar vista en rutas... urls.py de ctrl_comb... update porque carga datos
    # CARGAR EL SIN AUTORIZACION IMPORTADO DE BASES.... SINO NO SE PODRA EDITAR... implica un login url
    model=Modelo # enviar dato a la plantilla...
    template_name = "ctrl_comb/modelo_modal.html" #CAMBIAR A  MODAL... nueva ruta.. EN VEZ DE EDIT... la plantilla... pasar el nombre de la plantilla por ruta... listar modelo y luego urls.py
    context_object_name = "obj" # obj como nombre de contexto...
    form_class = ModeloForm # el formulario... envio POST de formulario... direccionar la salida que no se presione F5 para eso..
    # propiedad success url... se encarga de redireccionar a plantilla, en este caso a lista de modelos..
    success_url = reverse_lazy('control:modelo_list') # para la url.... control es el estatico..
    login_url = "usuarios:login" # para la url...
    permission_required = "ctrl_comb.change_modelo" # para el requerimiento.. de permiso de change modelo... para cambiar..


    # def form_valid(self, form): # recibe el formulario.... OJO INDENTADO....
    #     print(f"*********{form.instance.id} --- {self.request.user.id} *****************") 
    #     # f seria formato para que en la impresion se acepte tanto caracteres como numerico denotado por {}
    #     # el id seria para ver el formulario... y luego ver si existe el id... por user...
    #     if form.instance.id : # si el formulario existe
    #         form.instance.um = self.request.user # en el campo usuario modifica extrae el id... 
    #     else: # SINO la instancia del formulario del frontend no trae un id...
    #         form.instance.uc = self.request.user # poner valor al usuario crea

    #     return super().form_valid(form) # enviar el formulario...
    

# CREAR VISTA GENERICA DE CREATEVIEW PARA INSERTAR... PARA MODELO.. Y MODAL ESTA VEZ... AGREGAR NUEVA MARCA Y MODELO...

class ModeloNewModal(SinAutorizacion,MixinSaveUser,CreateView):
    model=Modelo # enviar dato a la plantilla...
    template_name = "ctrl_comb/modelo_modal.html" # PARA MODAL OJO la plantilla... pasar el nombre de la plantilla por ruta... listar modelo y luego urls.py
    context_object_name = "obj" # obj como nombre de contexto...
    form_class = ModeloForm # el formulario... envio POST de formulario... direccionar la salida que no se presione F5 para eso..
    # propiedad success url... se encarga de redireccionar a plantilla, en este caso a lista de modelos..
    success_url = reverse_lazy('control:modelo_list') # para la url.... control es el estatico..
    login_url = "usuarios:login" # para la url...
    permission_required = "ctrl_comb.add_modelo" # para el requerimiento.. de permiso de add modelo...


    # def form_valid(self, form): # recibe el formulario.... OJO INDENTADO....
    #     print(f"*********{form.instance.id} --- {self.request.user.id} *****************") 
    #     # f seria formato para que en la impresion se acepte tanto caracteres como numerico denotado por {}
    #     # el id seria para ver el formulario... y luego ver si existe el id... por user...
    #     if form.instance.id : # si el formulario existe
    #         form.instance.um = self.request.user # en el campo usuario modifica extrae el id... 
    #     else: # SINO la instancia del formulario del frontend no trae un id...
    #         form.instance.uc = self.request.user # poner valor al usuario crea

    #     return super().form_valid(form) # enviar el formulario...

# CREAR UNA FUNCION DE VISTA PARA ORM CON SERVER SIDE... PONER DECORADOR... PRIMERO AUTENTICAR Y LUEGO AUTORIZAR...
# las perms son variables de contexto de django para autorizacion y permisos...

@login_required(login_url="usuarios:login")  # donde redirigir en todo caso... si se trata de entrar al url de json... el dt...
@permission_required("ctrl_comb.view_modelo") # se puede ver el json si el USER LOGEADO TIENE PERMISO VIEW_MODELO...
def modelo_dt(request):
    context = {} # diccionario vacio agregar datos a enviar al frontend.
    datos = request.GET # envio por metodo GET, capturar lo que se esta solicitando... en variable datos guardar

    draw = int(datos.get("draw")) # POR SERVER SIDE... ES DE TIPO INT... se manda draw... leer lo que el frontend envia a backend..
    start = int(datos.get("start")) # para peticion arrancar... convertir a entero...
    # ahora la longitud...
    length = int(datos.get("length"))
    # paginacion de server side por busqueda... filtrar...
    search = datos.get("search[value]") # es string no entero... no precisa convertir... como en la pagina..

    # CONSULTA A BASE DE DATOS... Consultar todos los registros

    registros = Modelo.objects.all() # obtenemos todos los registros..

    if search: # esto es para la busqueda... filtrar...
        registros = registros.filter(
            Q(mark__descript__icontains = search) | # filtro contains... campo__propiedad__filtro... or logico |...
            Q(descript__icontains = search) # select * from modelo like search or descripcion de modelo..
            # al search en este caso POR MARCA.. se buscaara

        ) # del queryset podemos aplicar filtros... al conjunto de datos... por registros...

    recordsTotal = registros.count() # recibe la cantidad de registros...
    recordsFiltered = recordsTotal # numero total de registros filtrados...

    context["draw"] = draw # IR SUMANDO AL DICCIONARIO... PARA LOS DATOS...
    context["recordsTotal"] = recordsTotal # IR SUMANDO AL DICCIONARIO... PARA LOS DATOS...
    context["recordsFiltered"] = recordsTotal # filtros..

    # PROCEDER A HACER LA PAGINACION...
    # SEGMENTAR NUESTROS DATOS ACA... cantidad de registros por paginas

    reg = registros[start:start + length] # hacemos un slide de registros.. que comiencen por el 1... paginacion es de 10, 10 elementos empiezan en 10 en 10
    # + lenght que agregue los registros necesarios..
    paginator = Paginator(reg,length) # se manda cantidad de registros por pagina... son 4, 2 por pagina..

    # try catch para devolver la pagina por object
    try:
        obj = paginator.page(draw).object_list # representa en que pagina esta
    except PageNotAnInteger: # si fallase... error
        obj = paginator.page(draw).object_list # representa en que pagina esta
    except EmptyPage: # si da la excepcion de que la pagina esta vacia..
        obj = paginator.page(paginator.num_pages).object_list # representa en que pagina esta, cuando sea 1er pagina devuelve 1 con object list

    # TOCA FORMATEAR LOS DATOS COMO ESPERARIA PARA ENVIAR AL FRONTEND...
    # iterar obj

    # FORMA MAS TIPICA
    datos = [] # datos como lista vacia....
    for o in obj:
        datos.append({"id":o.id,"mark":o.mark.descript,"descript":o.descript}) # IR AGREGANDO A DATOS... id es nro de registro
    # descript es la marca y o. descript es modelo... ver bien...

    # ENVIAR AL FRONTEND... POR CONTEXTO...
    context["datos"] = datos # por datos... a traves de context agregando al diccionario...
    return JsonResponse(context,safe=False) #  enviando lista por eso es false... VER... serializar en formato que el frontend pueda interpretar mediante JSON... de web server a otras aplicaciones
    # CREAR RUTA....

# CREAR VISTA PARA VEHICULOS

class VehiculoList(SinAutorizacion,TemplateView):
    template_name="ctrl_comb/vehiculo.html" # nombre plantilla
    login_url="core:home" # que se vaya al principal a home
    permission_required = "ctrl_comb.view_modelo" # permiso requerido... por eso sinautorizacion
    # CREAR LUEGO LA RUTA EN URLS.PY DE CTRL_COMB


# ESTO ES PARA VEHICULO.HTML...

@login_required(login_url="usuarios:login")  # donde redirigir en todo caso... si se trata de entrar al url de json... el dt...
@permission_required("ctrl_comb.view_vehiculo") # se puede ver el json si el USER LOGEADO TIENE PERMISO VIEW_MODELO...
def vehiculo_dt(request): # nombre de la vista en vehiculo.html...
    context = {} # diccionario vacio agregar datos a enviar al frontend.
    datos = request.GET # envio por metodo GET, capturar lo que se esta solicitando... en variable datos guardar

    draw = int(datos.get("draw")) # POR SERVER SIDE... ES DE TIPO INT... se manda draw... leer lo que el frontend envia a backend..
    start = int(datos.get("start")) # para peticion arrancar... convertir a entero...
    # ahora la longitud...
    length = int(datos.get("length"))
    # paginacion de server side por busqueda... filtrar...
    search = datos.get("search[value]") # es string no entero... no precisa convertir... como en la pagina..

    # CONSULTA A BASE DE DATOS... Consultar todos los registros

    # registros = Modelo.objects.all() # obtenemos todos los registros.. FILTRAR
    if request.user.is_superuser:  # si el usuario que esta creando es superuser...
        registros = Vehiculo.objects.all() # que nos devuelva todos los registros...
    else: # SINO VAMOS A REQUERIR UN FILTRO...
        registros = Vehiculo.objects.filter(uc = request.user) # filtra para crear... para el usuario que hace peticion extrae
        # que el user sea el usuario crear


    if search: # esto es para la busqueda... filtrar...
        registros = registros.filter(
            Q(modelo__mark__descript__icontains = search) | 
            # filtro contains... campo__propiedad__filtro... or logico |... la descripcion de la marca 1ero ir a modelo luego en descript lo que se busca
            Q(modelo__descript__icontains = search) | # select * from modelo like search or descripcion de vehiculo.. PLACA
            Q(register__icontains = search) | # select * from register like search or descripcion de vehiculo..
            # register contiene el valor buscado numero de registro
            Q(year__icontains = search) # el anho..

            # al search en este caso POR MARCA.. se buscaara

        ) # del queryset podemos aplicar filtros... al conjunto de datos... por registros...

    recordsTotal = registros.count() # recibe la cantidad de registros...
    #recordsFiltered = recordsTotal # numero total de registros filtrados...

    context["draw"] = draw # IR SUMANDO AL DICCIONARIO... PARA LOS DATOS...
    context["recordsTotal"] = recordsTotal # IR SUMANDO AL DICCIONARIO... PARA LOS DATOS...
    context["recordsFiltered"] = recordsTotal # filtros..

    # PROCEDER A HACER LA PAGINACION...
    # SEGMENTAR NUESTROS DATOS ACA... cantidad de registros por paginas

    reg = registros[start:start + length] # hacemos un slide de registros.. que comiencen por el 1... paginacion es de 10, 10 elementos empiezan en 10 en 10
    # + lenght que agregue los registros necesarios..
    paginator = Paginator(reg,length) # se manda cantidad de registros por pagina... son 4, 2 por pagina..

    # try catch para devolver la pagina por object
    try:
        obj = paginator.page(draw).object_list # representa en que pagina esta
    except PageNotAnInteger: # si fallase... error
        obj = paginator.page(draw).object_list # representa en que pagina esta
    except EmptyPage: # si da la excepcion de que la pagina esta vacia..
        obj = paginator.page(paginator.num_pages).object_list # representa en que pagina esta, cuando sea 1er pagina devuelve 1 con object list

    # TOCA FORMATEAR LOS DATOS COMO ESPERARIA PARA ENVIAR AL FRONTEND...
    # iterar obj

    # FORMA MAS TIPICA
    datos = [
        {
            "id" : o.id, "mark":o.modelo.mark.descript,"modelo":o.modelo.descript,
            "register":o.register,"year":o.year
        } for o in obj
    ]


    # 1ERO PASAR POR MODELO.. descript es la marca y o. descript es modelo... ver bien... en la marca se toma la descripcion para madnar
    # a mark...

    # ENVIAR AL FRONTEND... POR CONTEXTO...
    context["datos"] = datos # por datos... a traves de context agregando al diccionario...
    return JsonResponse(context,safe=False) #  enviando lista por eso es false... VER... serializar en formato que el frontend pueda interpretar mediante JSON... de web server a otras aplicaciones
    # CREAR RUTA....


class VehiculoNewModal(SinAutorizacion,MixinSaveUser,CreateView):
    model=Vehiculo # enviar dato a la plantilla...
    template_name = "ctrl_comb/vehiculo_modal.html" # PARA MODAL OJO la plantilla... pasar el nombre de la plantilla por ruta... listar modelo y luego urls.py
    context_object_name = "obj" # obj como nombre de contexto...
    form_class = VehiculoForm # el formulario... envio POST de formulario... direccionar la salida que no se presione F5 para eso..
    # propiedad success url... se encarga de redireccionar a plantilla, en este caso a lista de vehiculos..
    success_url = reverse_lazy('control:vehiculo_list') # para la url.... control es el estatico..
    login_url = "usuarios:login" # para la url...
    permission_required = "ctrl_comb.add_vehiculo" # para el requerimiento.. de permiso de add vehiculo...
# CREAR FORMULARIO PARA VEHICULOS!! en forms.py del ctrl_comb... CREAR RUTA!

# sobreescribir get_context_data
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) # le enviamos los kwargs... simbolos
        context["marcas"] = Mark.objects.all() # todos los registros devolver... marcas
        context["modelos"] = Modelo.objects.all() # todos los registros devolver... modelo
        return context # retornar.... add dos contextos mas.. y contienen todos los registros de los campos marca y modelo
        # IR A PLANTILLA MODAL DE VEHICULO...




# PARA VEHICULO... MODAL... EDITAR CAMBIAR NOMBRE DE REGISTRO..

class VehiculoEditModal(SinAutorizacion,MixinSaveUser,UpdateView): # update es recargar... no olvidar agregar vista en rutas... urls.py de ctrl_comb... update porque carga datos
    # CARGAR EL SIN AUTORIZACION IMPORTADO DE BASES.... SINO NO SE PODRA EDITAR... implica un login url
    model=Vehiculo # enviar dato a la plantilla...
    template_name = "ctrl_comb/vehiculo_modal.html" #CAMBIAR A  MODAL... nueva ruta.. EN VEZ DE EDIT... la plantilla... pasar el nombre de la plantilla por ruta... listar modelo y luego urls.py
    context_object_name = "obj" # obj como nombre de contexto...
    form_class = VehiculoForm # el formulario... envio POST de formulario... direccionar la salida que no se presione F5 para eso..
    # propiedad success url... se encarga de redireccionar a plantilla, en este caso a lista de vehiculos..
    success_url = reverse_lazy('control:vehiculo_list') # para la url.... control es el estatico..
    login_url = "usuarios:login" # para la url...
    permission_required = "ctrl_comb.change_vehiculo" # para el requerimiento.. de permiso de change vehiculo... para cambiar..
    # COLOCAR EN URLS VEHICULO MODAL...

    # sobreescribir get_context_data... INDENTAR A LA CLASE... POR EL LAPICITO PARA QUE PUEDA EDITAR... Y CARGAR LOS DATOS...
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) # le enviamos los kwargs... simbolos
        context["marcas"] = Mark.objects.all() # todos los registros devolver... marcas
        context["modelos"] = Modelo.objects.all() # todos los registros devolver... modelo
        return context # retornar.... add dos contextos mas.. y contienen todos los registros de los campos marca y modelo
        # IR A PLANTILLA MODAL DE VEHICULO...


# PARA VEHICULO... MODAL... BORRAR NOMBRE DE REGISTRO.. VISTA PARA BORRAR...


class VehiculoDelete(DeleteView): # delete es borrado... no olvidar agregar vista en rutas... urls.py de ctrl_comb...
    model=Vehiculo # enviar dato a la plantilla...
    template_name = "bases/delete.html" # OJO! APUNTA A BASES... la plantilla... pasar el nombre de la plantilla por ruta... listar modelo y luego urls.py
    context_object_name = "obj" # obj como nombre de contexto...
    # propiedad success url... se encarga de redireccionar a plantilla, en este caso a lista de modelos..
    success_url = reverse_lazy('control:vehiculo_list') # para la url.... control es el estatico..
    # ir a urls.py..
