"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['192.168.0.4', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth', # para usuarios...
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # ALL AUTH... OJO PARA USUARIOS LOGIN
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google', # PARA USUARIOS POR GOOGLE..
    'allauth.socialaccount.providers.facebook',
    
    'crispy_forms', # se agrega para formularios crispy... mas formal
    'crispy_bootstrap5', # SIEMPRE POR ENCIMA DE APLICACIONES DEL PROYECTO OJASO!
    # LOCAL
    'bases', # local... django se da cuenta de la app bases y busca el directorio...
    'usuarios',
    'paginas',
    'ctrl_comb', # registrar siempre la ruta.... de la APLICACION..
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'allauth.account.middleware.AccountMiddleware', # agregar con el allauth... OJASO!!!
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"], # APUNTA EN BASE DIR, INDICA QUE DENTRO DE CADA APP HABRA UN DIRECTORIO TEMPLATE Y AHI BUSCA LA PLANTILLA
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request', # DEBE EXISTIR PARA LOGIN...
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "dj_ctl_comb",
        "USER": "postgres",
        "PASSWORD": "123", 
        "HOST": "db", # se debe cambiar para que no lea el local... de docker... db en compose...
        "PORT": "5432",
    }
}

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es-PY'

TIME_ZONE = 'America/Asuncion'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [  # para agregar carpetas externas con archivos estaticos... CSS O JS
    BASE_DIR / "static"
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "usuarios.Usuario" # Model es usuario y la app es usuarios...
LOGIN_REDIRECT_URL = "core:home" # cuando se logee se vaya al home url... sino aparece error 404... la ruta en home se llama core...
# abreviacion nomas es core...
LOGOUT_REDIRECT_URL = "core:home" # que rediriga a login...

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5" # NO OLVIDAR AGREGAR PARA CRISPY PARA CONFIGURAR AL PROYECTO... POR DEPENDENCIAS...
CRISPY_TEMPLATE_PACK = "bootstrap5"

# METODOS PARA USAR PARA AUTENTICAR... A DJANGO
AUTHENTICATION_BACKENDS = [
    # si usamos el login de django... por default
    'django.contrib.auth.backends.ModelBackend',
    # usando el allauth...
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1 # datos a migrar... con multiples usuarios.. SUPER IMPORTANTE...!




ACCOUNT_EMAIL_VERIFICATION = 'none' # verificacion por email... True si queremos...

SOCIALACCOUNT_PROVIDERS = {  # definimos para las redes sociales...
    'google': {  # PARA GOOGLE LOS REQUISITOS...
        'SCOPE': [
            'profile',
            'email'
        ],
        # parametros de autorizacion...
        'AUTH_PARAMS': {
            'access_type': 'online', # en linea... # type: ignore
            'prompt': 'select_account',
        },
        'OAUTH_PKCE_ENABLED': True,
    }

}

#ACCOUNT_EMAIL_REQUIRED = True
#ACCOUNT_USERNAME_REQUIRED = False
#ACCOUNT_AUTHENTICATION_METHOD = 'email'
#ACCOUNT_EMAIL_VERIFICATION = 'mandatory'

ACCOUNT_ADAPTER = 'allauth.account.adapter.DefaultAccountAdapter' # ESTO SI O SI PARA GOOGLE... SINO DARA ERROR AL LOGEARSE O CREAR USER...
SOCIALACCOUNT_ADAPTER = 'allauth.socialaccount.adapter.DefaultSocialAccountAdapter'

CSRF_TRUSTED_ORIGINS=['http://127.0.0.1:8000/','http://127.0.0.1/','http://192.168.0.4:8000/','http://localhost/']
SECURE_CROSS_ORIGIN_OPENER_POLICY = None
# SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"


SOCIALACCOUNT_AUTO_SIGNUP = True
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'


#LOGGING = {
#    'version': 1,
#    'disable_existing_loggers': False,
#    'handlers': {
#        'console': {
#            'class': 'logging.StreamHandler',
#        },
#    },
#    'root': {
#        'handlers': ['console'],
#        'level': 'DEBUG',
#    },
#    'django': {
#        'handlers': ['console'],
#        'level': 'DEBUG',
#        'propagate': False,
#    },
#    'django.request': {
#        'handlers': ['console'],
#        'level': 'DEBUG',
#        'propagate': False,
#    },
#}