from django.contrib.auth.models import BaseUserManager # importar el user manager... 
from django.utils.translation import gettext_lazy as _ # para la traducciones en paginas de idiomas abreviando como _ porque es largo
from django.utils import timezone # zona horaria...

class CustomUserManager(BaseUserManager):
    # crear cuerpo de usuario normal sin permiso de superusuario...
    # **kwargs es para leer un vector, lista o diccionario...
    def _create_user(self, email, username, first_name, password, **extra_fields): # con guion adelante para separar del metodo createuser...
        now = timezone.now() # tomar la hora para saber cuando se esta creando...

        if not email: # si no registro email... levantar error... POR LO MENOS REGISTRARLO... validacion...
            raise ValueError(_("El Email es Requerido")) # mensaje...
        if not first_name: # si no registro email... levantar error...
            raise ValueError(_("El Nombre es Requerido")) # mensaje...    
        
        # validacion o serializar el email
        email = self.normalize_email(email) # una vez normalizado procedemos a crear el user...
        user = self.model(email = email,
                          username = username, 
                          first_name = first_name,
                          last_login = now, # la ultima vez logeado....
                          **extra_fields
                          )
        
        user.set_password(password) # generar el hash de la contrasenha del user...
        user.save(using=self._db) # guardar... en la base de datos de DATABASES... en settings OJO
        return user # retorno de user... datos

    # definimos el metodo para crear usuario...
    def create_user(self, email, username, first_name, password, **otros_campos):
        return self._create_user(email, username, first_name, password, **otros_campos) # retorna la funcion anterior... sobreescribir

    # AHORA PARA CREAR SUPERUSUARIOS...
    def create_superuser(self, email, username, first_name, password, **otros_campos):
        otros_campos.setdefault('is_staff',True) # al kwargs le estamos agregando una llave is staff y va en true..
        otros_campos.setdefault('is_superuser',True) # si es superuser...
        otros_campos.setdefault('is_active',True) # si esta activo
        # set default se usa cuando los parametros enviados no son los indicados..
        # VALIDAR...
        if otros_campos.get('is_staff') is not True: # NO OLVIDAR EL GET!!! SINO EL SUPERUSER DARA ERROR AL CREAR.!!!
            raise ValueError(_("is_staff debe ser True para ser super usuario"))
        
        if otros_campos.get('is_superuser') is not True:
            raise ValueError(_("is_superuser debe ser True para ser super usuario"))
        
        return self._create_user(email, username, first_name, password, **otros_campos)