# importar el password y vistas para la aplicacion....
from django.urls import path, include # para el direccionamiento en url...
from django.contrib.auth import views as auth_views

from .views import * # importar todo del archivo de vistas...

app_name = "usuarios" # poner esto sino dara error... tiene que coincidir en home con el if usuarios: ... REDIRECIONA DE HOME ACA
# PARA AUTENTICARSE...

urlpatterns = [ # visualizar la direccion ip...
    path('',include('django.contrib.auth.urls')), # agregar ruta... con el usuario desde el principal... de la app..
    # en settings auth y middleware
    #path('login/',auth_views.LoginView.as_views(template_name="usuarios/login.html",name="login")),
    path('registro/',RegistoUsuarioView.as_view(),name="registro"), # dirige a vista... a la ubicacion de registro...
]

