from django.urls import path
from .views import * # importe todo en vistas...

app_name = "pages" # nombre de url...
urlpatterns = [ # conectar con el archivo de ruta principal en urls.py de app...
    path('about',AboutView.as_view(),name="about"), # para visualizar...
    path('forbidden',ForbiddenView.as_view(),name="forbidden"), # para visualizar... INVOCAR LA VISTA... PLANTILLA Y RUTA
    # EN LA MISMA CARPETA... OJO, ir a la vista de control modelolist en views de ctrl_comb....
]
