# Generated by Django 5.0.6 on 2024-07-19 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctrl_comb', '0001_initial'), # ESTA A DIFERENCIA DE INITIAL SI TIENE DEPENDENCIA PORQUE NO ES LA INICIAL... debe existir initial
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descript', models.CharField(db_comment='Descripcion del Modelo de Vehiculo', max_length=50)),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ctrl_comb.mark')), # A TABLA MARK...
            ],
            options={
                'verbose_name_plural': 'Modelos',
                'db_table_comment': 'Modelos de Vehiculos',
            },
        ),
    ]
