# Generated by Django 5.0.6 on 2024-07-26 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctrl_comb', '0002_modelo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelo',
            options={'permissions': [{'Puede Leer y Editar Modelos', 'permiso_especial'}], 'verbose_name_plural': 'Modelos'},
        ),
    ]
