# Generated by Django 5.0.6 on 2024-07-30 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctrl_comb', '0004_mark_estado_mark_fc_mark_fm_mark_uc_mark_um_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('register', models.CharField(db_column='Matricula Vehiculo', help_text='Matricula Vehiculo', max_length=50)),
                ('year', models.PositiveSmallIntegerField(help_text='Año del Vehiculo')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ctrl_comb.modelo')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('um', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vehiculos',
                'db_table_comment': 'Vehiculos',
            },
        ),
    ]
