from django.urls import path
from .views import * # importe todo...

app_name = "core" # nucleo..

urlpatterns = [ # mapea las urls...
    #path('',primera_vista,name="primera_vista") # 1er parametro es la url o home si no hay nada, 2do es la vista...
    # primera vista esta en views de bases...
    path('',HomeView.as_view(),name="home"), # cuando se basa en clase se pone as_view, si se basa en funcion no se pone.. 
    # al no tener nada en el primer parametro '' se recarga directo en 127.0.0.1:8000...
    # path('video_feed/', video_feed, name='video_feed'),  # URL para la transmisión de video
]